export default [
    {
        title: "Placeholder 1",
        slug: "xd",
        image: "https://via.placeholder.com/250/000000/FFFFFF/?text=PLACEHOLDER",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit sit amet",
        createdAt: Date.now(),
        author: {
            name: "Ricardo",
            image: "https://via.placeholder.com/100/000000/FFFFFF/?text=PLACEHOLDER",
        },
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat gravida. Pellentesque venenatis lacus at vehicula condimentum. Curabitur ornare nunc urna, id blandit est maximus a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vulputate tortor augue, id lacinia eros mattis a. Aliquam blandit erat vitae enim bibendum mattis. Ut non ligula congue, euismod risus et, semper odio. Quisque accumsan in lectus sit amet pretium. Duis egestas, lectus at placerat lobortis, sem dui convallis nibh, vel pretium enim erat at augue. Curabitur et orci nec sapien imperdiet pharetra. Aenean nec fringilla ligula, a efficitur diam. Vestibulum mattis at odio sit amet sodales. Quisque sollicitudin dolor erat, et cursus lacus dictum vel. Cras vel sagittis nibh. Phasellus a lorem purus. In hac habitasse platea dictumst. Maecenas volutpat aliquam libero, interdum accumsan erat egestas quis. Praesent efficitur, lorem at luctus suscipit, nunc lacus iaculis purus, sit amet finibus sapien neque eget purus. Phasellus blandit egestas turpis, eu ultricies nisl aliquet quis. Proin fringilla non turpis id lobortis. Integer porta varius nisi et consequat. Nam vel fermentum velit, eget bibendum mi. Suspendisse potenti. Praesent eget velit tellus. Curabitur mattis turpis vel varius mollis. Cras dictum dolor gravida, hendrerit risus ut, porttitor eros. Etiam id sem ac risus iaculis porttitor. Aliquam quis orci eget justo luctus imperdiet vel nec ante. Nulla lacinia sodales condimentum. Sed malesuada ipsum turpis, vitae imperdiet ex rhoncus molestie. Nulla mollis urna ut euismod facilisis. Morbi laoreet purus feugiat neque aliquet, ac elementum massa imperdiet. Vestibulum vestibulum ipsum sed porttitor lacinia. In vestibulum risus ac hendrerit egestas. Morbi tempor sapien ut nisl sollicitudin, in congue lorem venenatis. Ut tempus hendrerit ipsum vel porta. Duis id lobortis lacus, finibus pulvinar massa. Aenean pretium, magna eget varius consectetur, mauris nunc pulvinar metus, et rhoncus nunc quam sed odio. Ut ultricies scelerisque ligula. Sed quam nibh, faucibus nec est ac, efficitur efficitur ex. Sed sagittis lacinia massa, scelerisque vehicula libero feugiat at. In hac habitasse platea dictumst. Quisque lobortis ultrices dapibus. Phasellus a diam et lacus auctor porttitor. Pellentesque sed aliquet tortor."
    },
    {
        title: "Placeholder 2",
        slug: "placeholder2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit sit amet",
        image: "https://via.placeholder.com/250/000000/FFFFFF/?text=PLACEHOLDER",
        createdAt: Date.now(),
        author: {
            name: "Ricardo",
            image: "https://via.placeholder.com/100/000000/FFFFFF/?text=PLACEHOLDER",
        },
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat gravida. Pellentesque venenatis lacus at vehicula condimentum. Curabitur ornare nunc urna, id blandit est maximus a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vulputate tortor augue, id lacinia eros mattis a. Aliquam blandit erat vitae enim bibendum mattis. Ut non ligula congue, euismod risus et, semper odio. Quisque accumsan in lectus sit amet pretium. Duis egestas, lectus at placerat lobortis, sem dui convallis nibh, vel pretium enim erat at augue. Curabitur et orci nec sapien imperdiet pharetra. Aenean nec fringilla ligula, a efficitur diam. Vestibulum mattis at odio sit amet sodales. Quisque sollicitudin dolor erat, et cursus lacus dictum vel. Cras vel sagittis nibh. Phasellus a lorem purus. In hac habitasse platea dictumst. Maecenas volutpat aliquam libero, interdum accumsan erat egestas quis. Praesent efficitur, lorem at luctus suscipit, nunc lacus iaculis purus, sit amet finibus sapien neque eget purus. Phasellus blandit egestas turpis, eu ultricies nisl aliquet quis. Proin fringilla non turpis id lobortis. Integer porta varius nisi et consequat. Nam vel fermentum velit, eget bibendum mi. Suspendisse potenti. Praesent eget velit tellus. Curabitur mattis turpis vel varius mollis. Cras dictum dolor gravida, hendrerit risus ut, porttitor eros. Etiam id sem ac risus iaculis porttitor. Aliquam quis orci eget justo luctus imperdiet vel nec ante. Nulla lacinia sodales condimentum. Sed malesuada ipsum turpis, vitae imperdiet ex rhoncus molestie. Nulla mollis urna ut euismod facilisis. Morbi laoreet purus feugiat neque aliquet, ac elementum massa imperdiet. Vestibulum vestibulum ipsum sed porttitor lacinia. In vestibulum risus ac hendrerit egestas. Morbi tempor sapien ut nisl sollicitudin, in congue lorem venenatis. Ut tempus hendrerit ipsum vel porta. Duis id lobortis lacus, finibus pulvinar massa. Aenean pretium, magna eget varius consectetur, mauris nunc pulvinar metus, et rhoncus nunc quam sed odio. Ut ultricies scelerisque ligula. Sed quam nibh, faucibus nec est ac, efficitur efficitur ex. Sed sagittis lacinia massa, scelerisque vehicula libero feugiat at. In hac habitasse platea dictumst. Quisque lobortis ultrices dapibus. Phasellus a diam et lacus auctor porttitor. Pellentesque sed aliquet tortor."
    },
    {
        title: "Placeholder 3",
        slug: "placeholder3",
        image: "https://via.placeholder.com/250/000000/FFFFFF/?text=PLACEHOLDER",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit sit amet",
        createdAt: Date.now(),
        author: {
            name: "Ricardo",
            image: "https://via.placeholder.com/100/000000/FFFFFF/?text=PLACEHOLDER",
        },
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat gravida. Pellentesque venenatis lacus at vehicula condimentum. Curabitur ornare nunc urna, id blandit est maximus a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vulputate tortor augue, id lacinia eros mattis a. Aliquam blandit erat vitae enim bibendum mattis. Ut non ligula congue, euismod risus et, semper odio. Quisque accumsan in lectus sit amet pretium. Duis egestas, lectus at placerat lobortis, sem dui convallis nibh, vel pretium enim erat at augue. Curabitur et orci nec sapien imperdiet pharetra. Aenean nec fringilla ligula, a efficitur diam. Vestibulum mattis at odio sit amet sodales. Quisque sollicitudin dolor erat, et cursus lacus dictum vel. Cras vel sagittis nibh. Phasellus a lorem purus. In hac habitasse platea dictumst. Maecenas volutpat aliquam libero, interdum accumsan erat egestas quis. Praesent efficitur, lorem at luctus suscipit, nunc lacus iaculis purus, sit amet finibus sapien neque eget purus. Phasellus blandit egestas turpis, eu ultricies nisl aliquet quis. Proin fringilla non turpis id lobortis. Integer porta varius nisi et consequat. Nam vel fermentum velit, eget bibendum mi. Suspendisse potenti. Praesent eget velit tellus. Curabitur mattis turpis vel varius mollis. Cras dictum dolor gravida, hendrerit risus ut, porttitor eros. Etiam id sem ac risus iaculis porttitor. Aliquam quis orci eget justo luctus imperdiet vel nec ante. Nulla lacinia sodales condimentum. Sed malesuada ipsum turpis, vitae imperdiet ex rhoncus molestie. Nulla mollis urna ut euismod facilisis. Morbi laoreet purus feugiat neque aliquet, ac elementum massa imperdiet. Vestibulum vestibulum ipsum sed porttitor lacinia. In vestibulum risus ac hendrerit egestas. Morbi tempor sapien ut nisl sollicitudin, in congue lorem venenatis. Ut tempus hendrerit ipsum vel porta. Duis id lobortis lacus, finibus pulvinar massa. Aenean pretium, magna eget varius consectetur, mauris nunc pulvinar metus, et rhoncus nunc quam sed odio. Ut ultricies scelerisque ligula. Sed quam nibh, faucibus nec est ac, efficitur efficitur ex. Sed sagittis lacinia massa, scelerisque vehicula libero feugiat at. In hac habitasse platea dictumst. Quisque lobortis ultrices dapibus. Phasellus a diam et lacus auctor porttitor. Pellentesque sed aliquet tortor."
    },
    {
        title: "Placeholder 4",
        slug: "placeholder4",
        image: "https://via.placeholder.com/250/000000/FFFFFF/?text=PLACEHOLDER",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit sit amet",
        createdAt: Date.now(),
        author: {
            name: "Ricardo",
            image: "https://via.placeholder.com/100/000000/FFFFFF/?text=PLACEHOLDER",
        },
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat gravida. Pellentesque venenatis lacus at vehicula condimentum. Curabitur ornare nunc urna, id blandit est maximus a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vulputate tortor augue, id lacinia eros mattis a. Aliquam blandit erat vitae enim bibendum mattis. Ut non ligula congue, euismod risus et, semper odio. Quisque accumsan in lectus sit amet pretium. Duis egestas, lectus at placerat lobortis, sem dui convallis nibh, vel pretium enim erat at augue. Curabitur et orci nec sapien imperdiet pharetra. Aenean nec fringilla ligula, a efficitur diam. Vestibulum mattis at odio sit amet sodales. Quisque sollicitudin dolor erat, et cursus lacus dictum vel. Cras vel sagittis nibh. Phasellus a lorem purus. In hac habitasse platea dictumst. Maecenas volutpat aliquam libero, interdum accumsan erat egestas quis. Praesent efficitur, lorem at luctus suscipit, nunc lacus iaculis purus, sit amet finibus sapien neque eget purus. Phasellus blandit egestas turpis, eu ultricies nisl aliquet quis. Proin fringilla non turpis id lobortis. Integer porta varius nisi et consequat. Nam vel fermentum velit, eget bibendum mi. Suspendisse potenti. Praesent eget velit tellus. Curabitur mattis turpis vel varius mollis. Cras dictum dolor gravida, hendrerit risus ut, porttitor eros. Etiam id sem ac risus iaculis porttitor. Aliquam quis orci eget justo luctus imperdiet vel nec ante. Nulla lacinia sodales condimentum. Sed malesuada ipsum turpis, vitae imperdiet ex rhoncus molestie. Nulla mollis urna ut euismod facilisis. Morbi laoreet purus feugiat neque aliquet, ac elementum massa imperdiet. Vestibulum vestibulum ipsum sed porttitor lacinia. In vestibulum risus ac hendrerit egestas. Morbi tempor sapien ut nisl sollicitudin, in congue lorem venenatis. Ut tempus hendrerit ipsum vel porta. Duis id lobortis lacus, finibus pulvinar massa. Aenean pretium, magna eget varius consectetur, mauris nunc pulvinar metus, et rhoncus nunc quam sed odio. Ut ultricies scelerisque ligula. Sed quam nibh, faucibus nec est ac, efficitur efficitur ex. Sed sagittis lacinia massa, scelerisque vehicula libero feugiat at. In hac habitasse platea dictumst. Quisque lobortis ultrices dapibus. Phasellus a diam et lacus auctor porttitor. Pellentesque sed aliquet tortor."
    },
    {
        title: "Placeholder 5",
        slug: "placeholder5",
        image: "https://via.placeholder.com/250/000000/FFFFFF/?text=PLACEHOLDER",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit sit amet",
        createdAt: Date.now(),
        author: {
            name: "Ricardo",
            image: "https://via.placeholder.com/100/000000/FFFFFF/?text=PLACEHOLDER",
        },
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat gravida. Pellentesque venenatis lacus at vehicula condimentum. Curabitur ornare nunc urna, id blandit est maximus a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vulputate tortor augue, id lacinia eros mattis a. Aliquam blandit erat vitae enim bibendum mattis. Ut non ligula congue, euismod risus et, semper odio. Quisque accumsan in lectus sit amet pretium. Duis egestas, lectus at placerat lobortis, sem dui convallis nibh, vel pretium enim erat at augue. Curabitur et orci nec sapien imperdiet pharetra. Aenean nec fringilla ligula, a efficitur diam. Vestibulum mattis at odio sit amet sodales. Quisque sollicitudin dolor erat, et cursus lacus dictum vel. Cras vel sagittis nibh. Phasellus a lorem purus. In hac habitasse platea dictumst. Maecenas volutpat aliquam libero, interdum accumsan erat egestas quis. Praesent efficitur, lorem at luctus suscipit, nunc lacus iaculis purus, sit amet finibus sapien neque eget purus. Phasellus blandit egestas turpis, eu ultricies nisl aliquet quis. Proin fringilla non turpis id lobortis. Integer porta varius nisi et consequat. Nam vel fermentum velit, eget bibendum mi. Suspendisse potenti. Praesent eget velit tellus. Curabitur mattis turpis vel varius mollis. Cras dictum dolor gravida, hendrerit risus ut, porttitor eros. Etiam id sem ac risus iaculis porttitor. Aliquam quis orci eget justo luctus imperdiet vel nec ante. Nulla lacinia sodales condimentum. Sed malesuada ipsum turpis, vitae imperdiet ex rhoncus molestie. Nulla mollis urna ut euismod facilisis. Morbi laoreet purus feugiat neque aliquet, ac elementum massa imperdiet. Vestibulum vestibulum ipsum sed porttitor lacinia. In vestibulum risus ac hendrerit egestas. Morbi tempor sapien ut nisl sollicitudin, in congue lorem venenatis. Ut tempus hendrerit ipsum vel porta. Duis id lobortis lacus, finibus pulvinar massa. Aenean pretium, magna eget varius consectetur, mauris nunc pulvinar metus, et rhoncus nunc quam sed odio. Ut ultricies scelerisque ligula. Sed quam nibh, faucibus nec est ac, efficitur efficitur ex. Sed sagittis lacinia massa, scelerisque vehicula libero feugiat at. In hac habitasse platea dictumst. Quisque lobortis ultrices dapibus. Phasellus a diam et lacus auctor porttitor. Pellentesque sed aliquet tortor."
    },
]